// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmywxXfPFM-xS_Wcj4OUofRS54qGJQnto',
    appId: '1:524072964896:web:faab716ca9a00679cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    authDomain: 'habitin-ac425.firebaseapp.com',
    storageBucket: 'habitin-ac425.appspot.com',
    measurementId: 'G-XZ71TF52QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxTY65Xu1M2B3-pNBQ22uet7_Au10Quo',
    appId: '1:524072964896:android:515335a8a6819517cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmzNkQsTHrRNd47-zhN8NqkaZ9IcvJO0',
    appId: '1:524072964896:ios:2523dcbc1872fc68cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
    androidClientId: '524072964896-0sl0ogf70vnrf3c62nkjuc241gniad4p.apps.googleusercontent.com',
    iosClientId: '524072964896-j5aveliu8469if99ilgmgr9rt1lqgges.apps.googleusercontent.com',
    iosBundleId: 'com.metoly.habitin.habittin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmzNkQsTHrRNd47-zhN8NqkaZ9IcvJO0',
    appId: '1:524072964896:ios:40538f6f35357972cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
    androidClientId: '524072964896-0sl0ogf70vnrf3c62nkjuc241gniad4p.apps.googleusercontent.com',
    iosClientId: '524072964896-fae09unndo92dlksqtnsqq1nkck31l88.apps.googleusercontent.com',
    iosBundleId: 'com.metoly.habitin.habittin.RunnerTests',
  );
}
